version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - make install
  pre_build:
    commands:
      - make pre_build
  build:
    commands:
      - make build
  post_build:
    commands:
      - make post_build
artifacts:
  files:
    - '**/*'